// <auto-generated />
namespace StarToUp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class logon1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(logon1));
        
        string IMigrationMetadata.Id
        {
            get { return "201903250220306_logon1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
